USE sakila;

-- 1.List the number of films per category.
SELECT * FROM film_category as c
LEFT JOIN sakila.film AS f
ON c.film_id = f.film_id
ORDER BY c.category_id ASC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, a.address_id, c.city_id, c.country_id FROM sakila.store AS s
JOIN sakila.city AS c
ON c.city_id = c.country_id
JOIN sakila.address AS a
ON s.address_id = a.address_id
ORDER BY s.store_id;

-- 3. Calculate the total revenue generated by each store in dollars.
-- Where is the info? tables: payment, staff, stores
SELECT * FROM sakila.payment;

SELECT s.store_id, SUM(p.amount) as 'Total Revenue' FROM sakila.payment AS p
JOIN sakila.staff AS f 
ON p.staff_id = f.staff_id
JOIN sakila.store AS s
ON f.store_id = s.store_id
GROUP BY s.store_id;






